version: '3.7'

services:

  frontend:
    container_name: bn-frontend
    build: ./frontend
    ports:
      - '3000:80'
    environment:
      - VIRTUAL_HOST=blocknotify.net
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=blocknotify.net
      - LETSENCRYPT_EMAIL=admin@blocknotify.net
    restart: always

  backend:
    container_name: bn-backend
    build: ./backend
    ports:
      - '8000:80'
    environment:
      - VIRTUAL_HOST=api.blocknotify.net
      - LETSENCRYPT_HOST=api.blocknotify.net
      - LETSENCRYPT_EMAIL=admin@blocknotify.net
    restart: always

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

volumes:
  vhost:
  html:
  certs:
  dhparam:
  acme:
  conf:

networks:
  default:
    name: nginx-proxy
